/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlincoroutine

fun main() {
    val coroutineExample = CoroutineExample()
    coroutineExample.doOperationSplit()
}
